### ISSUE TITLE
Mending on books is not removed

### ISSUE THREAD

**Issue by Folas1337** [YouHaveTrouble/MendingBeGone#1]
It appears as though the plugin still removes mending from items, it doesn't do so for enchanted books :(

Running latest version of paper, 1.1 of MendingBeGone and no matter what I do to the book, it'll keep being Mending.
![image](https://github.com/YouHaveTrouble/MendingBeGone/assets/39222968/d1b53085-9286-4a56-a52f-0332a6c8582c)

**Comment by Folas1337** [comment]
OK, to be fair it was happening in production and test was still running 1.20.1

But I was able to also reproduce it on the test server after updating to 1.20.2:
![image](https://github.com/YouHaveTrouble/MendingBeGone/assets/39222968/254072d9-80a7-4343-8cbc-d39e32de49d2)

**Comment by YouHaveTrouble** [comment]
Fixed in [this release](https://modrinth.com/plugin/mending-be-gone/version/9sSdet8q)
