### ISSUE TITLE
Villager trades with Mending get removed rather than replaced

### ISSUE THREAD

**Issue by Folas1337** [YouHaveTrouble/MendingBeGone#2]
I created a villager that had Mending as a trade, then installed MendingBeGone and noticed how afterwards the trade was removed entirely which I think shouldn't happen and instead it should turn it into a trade with Unbreaking 3.

I think this is probably because the plugin's not quite compatible with 1.21 anymore. I hope there will be a fix to this soon :)

**Comment by YouHaveTrouble** [comment]
This is technically not a bug, as the behavior is clearly listed in the plugin's readme file, but I can see how it can be seen as inconsistent. I'll see if I can quickly patch it up.

**Comment by Folas1337** [comment]
Oh, then I just didn't notice until now, sorry for the confusion then.

Thanks for still considering it though :)

**Comment by YouHaveTrouble** [comment]
If you hop on [discord](https://discord.youhavetrouble.me) I can send you a jar with possible change
